import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/frontend/Header";
import Footer from "@/components/frontend/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["300","400", "500","600", "700"]  });

export const metadata = {
  title: "Eatsy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="min-h-screen flex flex-col justify-between">
          <Header />
          <main className="w-full flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
